import Head from "next/head";

import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>1-1 Chat</title>
        <meta name="description" content="Generated by whatsapp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />
    </div>
  );
}
